module.exports = {
    rootDir: "./",
    clearMocks: true,
    // resetMocks: true,
    resetModules: true,
    transform: {
        "^.+\\.[tj]s$": ["ts-jest", { isolatedModules: true }],
    },
    collectCoverageFrom: [
        "**/handlers/**/*{.js,.ts,.tsx}",
        "!**/node_modules/**",
        "!**/handlers/multerutil.js",
        "!**/handlers/tpoupload.js",
        "!**/handlers/tools/log.js",
        "!**/common/*{.js,.ts,.tsx}",
        "!**/conf/*{.js,.ts,.tsx}",
        "!**/core/*{.js,.ts,.tsx}",
        "!**/doc/*{.js,.ts,.tsx}",
        "!**/runtime/*{.js,.ts,.tsx}",
        "!**/serve/*{.js,.ts,.tsx}",
        "!**/handlers/proxyroutes.js",
    ],
    coverageDirectory: "testResult",
    coverageReporters: ["json", "lcov", "text", "clover", "html", "cobertura"],
    preset: "ts-jest/presets/js-with-ts",
    testEnvironment: "node",
    maxWorkers: "50%",
    testPathIgnorePatterns: ["\\\\node_modules\\\\"],
    testRegex: "(/test/.*\\.(test|spec))\\.[tj]s$",
    verbose: true,
    reporters: [
        "default",
        [
            "jest-junit",
            {
                suiteName: "studio web service tests",
                outputDirectory: "testResult/junitResult",
                outputName: "junit-ut.xml",
                classNameTemplate: "{classname}-{title}",
                titleTemplate: "{classname}-{title}",
                ancestorSeparator: " › ",
                usePathForSuiteName: "true",
            },
        ],
    ],
};
